accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('profile/list/', views.profile_list, name='profile_list'),
    path('profile/<int:user_id>/', views.profile_detail, name='profile_detail'), 
    path('user-profile/', views.user_profile, name='user_profile'),
]

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import create_blog

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pages/', views.pages, name='pages'),
    path('pages/<int:blog_id>/', views.page_detail, name='page_detail'),
    path('create/', create_blog, name='create_blog'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('delete/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('pages/<int:blog_id>/', views.page_detail, name='blog_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

futbol_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog import views as blog_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', blog_views.home, name='home'),
    path('messages/', include('messaging.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_photos', blank=True, null=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from .models import Profile

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo', 'description']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm
from .models import Profile



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

@login_required
def profile(request):
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = None
    
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            profiles = Profile.objects.all()
            return render(request, 'accounts/profile_list.html', {'profiles': profiles})
    else:
        form = ProfileUpdateForm(instance=profile)
    
    return render(request, 'accounts/profile.html', {'form': form})



def profile_view(request):
    return render(request, 'blog/profile.html')

def edit_profile(request):
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = None
    
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            print("Perfil editado correctamente")  
            return redirect('profile_list')  
    else:
        form = ProfileUpdateForm(instance=profile)
    
    return render(request, 'accounts/edit_profile.html', {'form': form})

@login_required
def profile_list(request):
    profiles = Profile.objects.all() 
    return render(request, 'accounts/profile_list.html', {'profiles': profiles})


def profile_detail(request, user_id):
    profile = get_object_or_404(Profile, user__id=user_id)
    return render(request, 'accounts/profile_detail.html', {'profile': profile})

@login_required
def user_profile(request):
    profile = request.user.profile 
    return render(request, 'accounts/user_profile.html', {'profile': profile})

accounts/templates/accounts/edit_profile.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>{{ user.username }}</h1>
    {% if profile.photo %}
        <img src="{{ profile.photo.url }}" alt="Profile Photo">
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="photo" class="file-input" id="id_photo">
        <label for="id_photo" class="choose-photo green-button">Elegir foto</label>
        <br><br>
        <textarea name="description" rows="4" cols="50">{{ profile.description }}</textarea>
        <br><br>
        <button type="submit" class="green-button">Guardar</button> 
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'blog/base.html' %}

{% block title %}Iniciar sesión{% endblock %}

{% block content %}
    <h2>Iniciar sesión</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar sesión</button>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}
{% block title %}Perfil{% endblock %}
{% block content %}
<h1>Perfil</h1>
<a class="new-blog-link" href="{% url 'edit_profile' %}">Editar perfil</a>
<a class="new-blog-link" href="{% url 'profile_list' %}">Ver listado de perfiles</a>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Detalles del Perfil{% endblock %}

{% block content %}
<h1>Perfil de {{ profile.user.username }}</h1>
{% if profile.photo %}
    <img src="{{ profile.photo.url }}" alt="Profile Photo" width="150" height="150">
{% else %}
    <p>No hay foto de perfil</p>
{% endif %}
<p>Descripción: {{ profile.description }}</p>
<a class="green-button" href="{% url 'profile_list' %}">Volver a la lista de perfiles</a>
{% endblock %}

accounts/templates/accounts/profile_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Lista de Perfiles{% endblock %}

{% block content %}
<h1>Lista de Perfiles</h1>
<ul>
    {% for profile in profiles %}
        <li>
            <h2>{{ profile.user.username }}</h2>
            <a class="green-button" href="{% url 'profile_detail' profile.user.id %}">Ver detalles</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'blog/base.html' %}

{% block title %}Registrarse{% endblock %}

{% block content %}
    <h2>Registrarse</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
{% endblock %}