blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import create_blog

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pages/', views.pages, name='pages'),
    path('pages/<int:blog_id>/', views.page_detail, name='page_detail'),
    path('create/', create_blog, name='create_blog'),
    path('blogs/', views.blog_list, name='blog_list'),
    path('delete/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('pages/<int:blog_id>/', views.page_detail, name='blog_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

futbol_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog import views as blog_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', blog_views.home, name='home'),
    path('messages/', include('messaging.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Blog(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='blog_images/')

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

blog/forms.py
from django import forms
from .models import Blog, Comment

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'subtitle', 'body', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog, Comment
from .forms import BlogForm,CommentForm
from django.contrib.auth.decorators import login_required

def home(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/home.html', {'blogs': blogs})

def about(request):
    return render(request, 'blog/about.html')

def pages(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/pages.html', {'blogs': blogs})

def page_detail(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    comments = Comment.objects.filter(blog=blog)  
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.blog = blog
            comment.save()
            return redirect('blog_detail', blog_id=blog_id)
    else:
        form = CommentForm()
    return render(request, 'blog/blog_detail.html', {'blog': blog, 'form': form, 'comments': comments})

@login_required
def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.save()
            return redirect('blog_list')  
    else:
        form = BlogForm()
    return render(request, 'blog/create_blog.html', {'form': form})

@login_required
def blog_list(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/blog_list.html', {'blogs': blogs})

@login_required
def delete_blog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.user == blog.author:
        blog.delete()
    return redirect('blog_list')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}
<h1>Luciano Bertini</h1>
<p>Soy de Wilde, Buenos Aires. Tengo 24 años y actualmente me encuentro estudiando Desarrollo de Software en UADE. A su vez, me encuentro complementando estudios en Coderhouse.</p>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Fútbol Blog{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/styles.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
    </style>
</head>
<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'about' %}">About</a>
        <a href="{% url 'pages' %}">Blogs</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">Perfil</a>  
            <a href="{% url 'inbox' %}">Bandeja de entrada</a>
            <a href="{% url 'send_message' %}">Enviar mensaje</a>
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'signup' %}">Signup</a>
        {% endif %}
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ blog.title }}{% endblock %}

{% block content %}
    <h1>{{ blog.title }}</h1>
    <h2>{{ blog.subtitle }}</h2>
    {% if blog.image %}
        <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
    {% endif %}
    <p>{{ blog.body }}</p>
    <p>Autor: {{ blog.author.username }}</p>
    <p>Fecha: {{ blog.date }}</p>

    <!-- Formulario de comentarios -->
    <form method="post" action="{% url 'page_detail' blog.id %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            <textarea class="form-control" id="id_content" name="content" rows="3" placeholder="Escribe tu comentario aquí"></textarea>
        </div>
        <button class="green-button" type="submit">Comentar</button>
    </form>

    <h2>Comentarios:</h2>
    <ul>
        {% for comment in comments %}
            <li>
                <p>{{ comment.content }}</p>
                <p>Por: {{ comment.author.username }} el {{ comment.created_at }}</p>
            </li>
        {% empty %}
            <p>No hay comentarios aún.</p>
        {% endfor %}
    </ul>

    <a class="green-button" href="{% url 'blog_list' %}">Volver al listado de blogs</a>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Blogs{% endblock %}

{% block content %}
<h1>Lista de Blogs</h1>
<ul>
    {% for blog in blogs %}
        <li>
            <h2>{{ blog.title }}</h2>
            <p>Usuario: {{ blog.author.username }}</p> 
            <a class="green-button" href="{% url 'page_detail' blog.id %}">Ver detalles</a> 
            {% if user.is_authenticated and user == blog.author %}
                <form action="{% url 'delete_blog' blog.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button class="red-button" type="submit">Eliminar</button>
                </form>
            {% endif %}
        </li>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/create_blog.html
{% extends 'blog/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="create-blog-container">
    <h2 class="create-blog-heading">{% trans 'Crear un nuevo blog' %}</h2>
    <form class="create-blog-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">{% trans 'Título' %}:</label>
            <br>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_subtitle">{% trans 'Subtítulo' %}:</label>
            <br>
            {{ form.subtitle }}
        </div>
        <div class="form-group">
            <label for="id_body">{% trans 'Cuerpo' %}:</label>
            <br>
            {{ form.body }}
        </div>
        <div class="form-group" style="margin-bottom: 10px;">
            <label for="id_image">{% trans 'Imagen' %}:</label>
            <br>
            {{ form.image }}
        </div>
        <div class="form-group">
            <label for="id_image" class="green-button">Elegir archivo</label>
        </div>
    </div>
        <button class="create-blog-button green-button" type="submit">{% trans 'Crear blog' %}</button>
    </form>
</div>
<style>
    .form-group {
        margin-bottom: 20px; 
    }
</style>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>FutbolBlog</h1>
{% endblock %}

blog/templates/blog/page_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ blog.title }}{% endblock %}

{% block content %}
    <h1>{{ blog.title }}</h1>
    <h2>{{ blog.subtitle }}</h2>
    {% if blog.image %}
        <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
    {% endif %}
    <p>{{ blog.body }}</p>
    <p>Autor: {{ blog.author.username }}</p>
    <p>Fecha: {{ blog.date }}</p>
    <a class="green-button" href="{% url 'blog_list' %}">Volver a la lista de blogs</a>
{% endblock %}

blog/templates/blog/pages.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Blogs{% endblock %}

{% block content %}
<h1>Blogs</h1>
<a class="new-blog-link" href="{% url 'create_blog' %}">Crear nuevo blog</a>
<a class="new-blog-link" href="{% url 'blog_list' %}">Ver listado de blogs</a>
{% endblock %}